cloud:
  aws:
    credentials:
      accessKey:  ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    region:
      static:  us-east-1
    stack:
      auto: false
      
queue:
  from: base_unica_jms_persistir